### ISSUE TITLE
RecursionError: maximum recursion depth exceeded?

### ISSUE THREAD

**Issue by bmorrissirromb** [iann0036/cfn-hooks#3]
Do you get 'RecursionError: maximum recursion depth exceeded' when building this hook due to the large number of resource types it uses?

I've been getting that error and am not sure what to do with it other than breaking the hook down into hooks with smaller chunks of resource types.

**Comment by iann0036** [comment]
Didn't personally get this, no. Would be interested to see if you find out more.
