### ISSUE TITLE
New CFN Resource Strategy

### ISSUE THREAD

**Issue by bmorrissirromb** [iann0036/cfn-hooks#4]
Do you have a strategy for adding new CFN resource types as they get added by the CloudFormation team?

**Comment by iann0036** [comment]
@PatMyron has already helped get us started on this per https://github.com/iann0036/cfn-hooks/blob/main/.github/workflows/maintenance.yaml

I'll need to extend this to fix the missing types in the spec, and auto-publish to the registry, probably in the format `MAJOR.MINOR.20221234`
